#!/bin/sh

if ! command -v fs >/dev/null 2>&1; then
  echo "Error: 'fs' is not installed or not in your PATH." >&2
  echo "Please install it from https://github.com/Squirreljetpack/fist" >&2
  exit 1
fi

if [ -t 0 ]; then
  ob-vaults -g "$@"
else
  cat
fi |
while read -r line
do
  FS_OUTPUT="{=}\t{-1.}" fs -t .md --list --no-read "$line" .
done |
FS_OPTS='opener=ob-open display-batch=[while (($#)); do print ${${1#*/$2/}%.md}; shift 2; done] delim=\t' fs