use crate::{
    AcceptHook, Matchmaker,
    config::{
        ColumnsConfig, ExitConfig, PreprocessConfig, RenderConfig, StringOrInt, TerminalConfig,
        WorkerConfig,
    },
    nucleo::{Column, Worker, injector::WorkerInjector},
    render::{EventHandlers, InterruptHandlers, MMState},
    utils::text::{self, sanitize_string},
};

use ansi_to_tui::IntoText;
use ratatui::text::Text;
use std::{borrow::Cow, sync::Arc};

pub struct OddEnds {
    pub hidden_columns: Vec<usize>,
    pub has_error: bool,
    /// Factory producing per-column range lookups. Given a column index `n`,
    /// returns a closure that maps an input `&String` to the `(start, end)`
    /// byte range of its `n`-th segment. The factory mirrors the trim/ansi
    /// handling of [`build_columns`]'s preprocessors, so the returned ranges
    /// align with the bytes a column would render.
    pub ranges_fn: RangesFactory<String>,
}

/// A closure that, given an input string, returns the extracted substring
/// for one of its column segments. Returns `Cow::Borrowed` when the segment
/// can be obtained directly from the input (no ANSI stripping required) and
/// `Cow::Owned` when the preprocessor had to materialize a plain copy
/// (e.g. after stripping ANSI escapes).
pub type RangesFn<T> = Arc<dyn for<'a> Fn(&'a T) -> Cow<'a, str> + Send + Sync>;

/// A factory: given a column index `n`, returns a [`RangesFn`] for that
/// column. Cloning the `Arc` is cheap; calling with a new `n` produces a
/// fresh per-column lookup closure.
pub type RangesFactory<T> = Arc<dyn Fn(usize) -> RangesFn<T> + Send + Sync>;

pub type ConfigMatchmaker = Matchmaker<String, String, ConfigPreprocessedData>;

impl ConfigMatchmaker {
    #[allow(unused)]
    /// Creates a new Matchmaker from a config::BaseConfig.
    /// Calls [`Matchmaker::prepare`];
    pub fn new_from_config(
        render_config: RenderConfig,
        tui_config: TerminalConfig,
        worker_config: WorkerConfig,
        columns_config: ColumnsConfig,
        exit_config: ExitConfig,
        preprocess_config: PreprocessConfig,
    ) -> (Self, ConfigInjector, OddEnds) {
        let mut has_error = false;

        let cc = columns_config;
        let hidden_columns = cc
            .names
            .iter()
            .enumerate()
            .filter_map(|(i, x)| x.hidden.then_some(i))
            .collect();

        // Build columns (also builds and truncates column_names internally).
        let (columns, raw_preprocessor, text_preprocessor, ranges_fn) =
            build_columns(&cc, preprocess_config);

        // Resolve default column from the names attached to the built columns.
        let default_index = default_column(&cc, &columns);

        let mut worker = Worker::new(columns, default_index, raw_preprocessor, text_preprocessor);

        worker.reverse_items(worker_config.reverse);
        worker.set_stability(*worker_config.sort_threshold);
        for (i, c) in cc.names.iter().enumerate() {
            worker.set_column_options(i, c.options)
        }

        let injector = worker.injector();

        // Build the default accept_hook: returns empty Vec<String> by default.
        // The CLI overrides this in `start.rs` via the `on_accept`/`output_template`
        // logic. The hook is just a placeholder for the structural refactor; the
        // real accept pipeline will replace it.
        let accept_hook = Box::new(
            |_state: &mut MMState<'_, '_, String, ConfigPreprocessedData>| -> Vec<String> {
                vec![]
            },
        ) as AcceptHook<String, ConfigPreprocessedData, String>;

        let event_handlers = EventHandlers::new();
        let interrupt_handlers = InterruptHandlers::new();

        let mut new = Matchmaker {
            worker,
            render_config,
            tui_config,
            exit_config,
            output: accept_hook,
            event_handlers,
            interrupt_handlers,
        };
        new.prepare();

        let misc = OddEnds {
            hidden_columns,
            has_error,
            ranges_fn,
        };

        (new, injector, misc)
    }
}

/// Preprocessed data type for config-based columns
/// Contains: (Result<Text, raw_string>, split_ranges)
pub type ConfigPreprocessedData = (Result<Text<'static>, String>, Vec<(u32, u32)>);
pub type ConfigInjector = WorkerInjector<String, ConfigPreprocessedData>;

/// Build columns for config-based matchmaker with preprocessing support.
///
/// `column_names` is built from `cc` (either from `cc.names` or autogenerated
/// from `cc.max_cols` and `cc.names_from_zero`). For `Split::Delimiter` with
/// unnamed capture groups, and for `Split::Regexes`, the built names are
/// truncated to the number of capture groups / regexes respectively.
///
/// Returns `(columns, raw_preprocessor, text_preprocessor, ranges_fn)`. The
/// default column is *not* resolved here — call [`default_column`] afterwards
/// with the returned columns. `ranges_fn` is a factory producing per-column
/// range lookups (see [`RangesFactory`]) and mirrors the `trim`/`ansi`
/// behavior of the other preprocessors.
pub fn build_columns(
    cc: &ColumnsConfig,
    PreprocessConfig {
        ansi,
        trim,
        sanitize,
        require_column,
    }: PreprocessConfig, // (parse_ansi, trim, skip_empty)
) -> (
    Vec<Column<String, ConfigPreprocessedData>>,
    Arc<dyn Fn(&String) -> Option<ConfigPreprocessedData> + Send + Sync>,
    Arc<dyn Fn(&String) -> ConfigPreprocessedData + Send + Sync>,
    RangesFactory<String>,
) {
    use crate::config::Split;
    use regex::Regex;

    let offset = !cc.names_from_zero as usize;

    // Build column names from cc.
    let mut column_names: Vec<Arc<str>> = if cc.names.is_empty() {
        (offset..(cc.max_cols() + offset))
            .map(|n| Arc::from(n.to_string()))
            .collect()
    } else {
        cc.names
            .iter()
            .take(cc.max_cols())
            .map(|s| Arc::from(s.name.as_str()))
            .collect()
    };

    // Split::None -> single column with an empty name (matches historical behavior).
    if matches!(cc.split, Split::None) {
        column_names = vec![Arc::from("")];
    }

    // Truncate column_names to the number of capture groups (unnamed) or regexes for a quick optimization.
    match &cc.split {
        Split::Delimiter(rg) => {
            let has_named = rg.capture_names().skip(1).any(|n| n.is_some());
            let has_unnamed = rg.captures_len() > 1 && !has_named;
            if has_unnamed {
                column_names.truncate(rg.captures_len() - 1);
            }
        }
        Split::Regexes(rgs) => {
            column_names.truncate(rgs.len());
        }
        // CSV field count is dynamic, leave column_names as configured.
        Split::CSV(_) => {}
        Split::None => {}
    }

    let split = cc.split.clone();
    let col_count = column_names.len();

    // Build split function based on config
    let split_fn: Arc<dyn Fn(&str) -> Vec<(u32, u32)> + Send + Sync> = match &split {
        Split::Delimiter(rg) => {
            let rg = rg.clone();
            let column_names_clone = column_names.clone();
            let mut has_named_group = false;

            // Map named captures to column indices
            let capture_to_idx: Vec<Option<usize>> = rg
                .capture_names()
                .enumerate()
                .map(|(i, name_opt)| {
                    if i == 0 {
                        None
                    } else {
                        name_opt.and_then(|name| {
                            has_named_group = true;
                            column_names_clone.iter().position(|n| n.as_ref() == name)
                        })
                    }
                })
                .collect();

            // Determine the mode:
            // 1. Named captures -> capture_to_idx has at least one Some
            // 2. All unnamed -> capture_to_idx has at least one None beyond index 0
            // 3. No capture groups -> captures_len() == 1
            let has_unnamed = rg.captures_len() > 1 && !has_named_group;

            if has_named_group {
                log::debug!("Named regex: {rg} with {} groups", capture_to_idx.len());

                // Named capture groups
                Arc::new(move |s: &str| {
                    let mut ranges = vec![(0u32, 0u32); col_count];

                    if let Some(caps) = rg.captures(s) {
                        for (group_idx, col_idx_opt) in capture_to_idx.iter().enumerate().skip(1) {
                            if let Some(col_idx) = col_idx_opt {
                                if let Some(m) = caps.get(group_idx) {
                                    ranges[*col_idx] = (m.start() as u32, m.end() as u32);
                                }
                            }
                        }
                    }

                    ranges
                })
            } else if has_unnamed {
                log::debug!(
                    "Unnamed regex: {rg} with {} groups",
                    capture_to_idx.len() - 1
                );

                // All unnamed capture groups -> map in order
                Arc::new(move |s: &str| {
                    let mut ranges = vec![(0u32, 0u32); col_count];
                    if let Some(caps) = rg.captures(s) {
                        for (i, group) in caps.iter().skip(1).enumerate().take(col_count) {
                            if let Some(m) = group {
                                ranges[i] = (m.start() as u32, m.end() as u32);
                            }
                        }
                    }

                    ranges
                })
            } else {
                log::debug!("Delimiter regex: {rg}");

                // No capture groups -> normal delimiter split
                Arc::new(move |s: &str| {
                    let mut ranges = Vec::with_capacity(col_count);
                    let mut last_end = 0;

                    for m in rg.find_iter(s).take(col_count - 1) {
                        ranges.push((last_end as u32, m.start() as u32));
                        last_end = m.end();
                    }

                    ranges.push((last_end as u32, s.len() as u32));
                    ranges
                })
            }
        }
        // allows nontrivial overlaps but rarely useful
        Split::Regexes(rgs) => {
            let rgs: Vec<Regex> = rgs.clone();
            Arc::new(move |s: &str| {
                let mut ranges = Vec::with_capacity(col_count);
                let mut last_end = 0;

                for re in rgs.iter().take(col_count) {
                    if last_end <= s.len() {
                        if let Some(m) = re.find(&s[last_end..]) {
                            let start = last_end + m.start();
                            let end = last_end + m.end();
                            ranges.push((start as u32, end as u32));
                            last_end = end;
                            continue;
                        }
                    }
                    ranges.push((0, 0));
                }
                ranges
            })
        }
        // RFC 4180 CSV/TSV split. The byte-level state machine handles:
        //   - `"` at the start of a field opens a quoted field
        //   - delimiters and newlines inside a quoted field are literal
        //   - `""` inside a quoted field is an escaped `"`
        //   - `"` mid-field outside of quotes is literal (strict RFC 4180)
        // The emitted ranges point to the unquoted field content (surrounding
        // quotes excluded; `""` is preserved as two bytes — consumers can
        // decode it if they want).
        Split::CSV(tab) => {
            let delim: u8 = if *tab { b'\t' } else { b',' };
            Arc::new(move |s: &str| {
                let bytes = s.as_bytes();
                let len = bytes.len();
                // Take col_count - 1 delimiters (capped); the remainder merges
                // into the final column. Mirrors the Delimiter no-capture path.
                let max_splits = col_count.saturating_sub(1);
                let mut ranges: Vec<(u32, u32)> = Vec::with_capacity(col_count);
                let mut field_start: usize = 0;
                // `field_end` is the exclusive end of the current field's
                // content. For a quoted field it's the closing-quote position;
                // for an unquoted field it tracks the latest char position.
                let mut field_end: usize = 0;
                let mut in_quoted = false;
                let mut i: usize = 0;
                let mut splits_taken: usize = 0;

                while i < len {
                    let c = bytes[i];
                    if c == b'"' && i == field_start && !in_quoted {
                        // Open a quoted field.
                        in_quoted = true;
                        field_start = i + 1;
                        field_end = field_start;
                        i += 1;
                    } else if c == b'"' && in_quoted {
                        // Inside a quoted field: `""` is an escape, else close.
                        if i + 1 < len && bytes[i + 1] == b'"' {
                            i += 2;
                        } else {
                            in_quoted = false;
                            // Field content ends at the closing quote.
                            field_end = i;
                            i += 1;
                        }
                    } else if c == delim && !in_quoted {
                        if splits_taken < max_splits {
                            ranges.push((field_start as u32, field_end as u32));
                            field_start = i + 1;
                            field_end = i + 1;
                            splits_taken += 1;
                        } else {
                            // Cap reached: this delimiter (and everything after)
                            // is absorbed into the final merged field.
                            field_end = i + 1;
                        }
                        i += 1;
                    } else {
                        // Regular char: advance field_end to after this char
                        // in both modes, so an unclosed-quote line still
                        // extends the last field to end-of-input.
                        field_end = i + 1;
                        i += 1;
                    }
                }
                ranges.push((field_start as u32, field_end as u32));
                ranges
            })
        }
        Split::None => Arc::new(move |s: &str| vec![(0u32, s.len() as u32)]),
    };

    // Build raw preprocessor (returns string representation)
    let raw_preprocessor: Arc<dyn Fn(&String) -> Option<ConfigPreprocessedData> + Send + Sync> = {
        let split_fn = split_fn.clone();
        let split_clone = split.clone();
        Arc::new(move |item: &String| {
            let s = if trim {
                item.trim().to_string()
            } else {
                item.clone()
            };

            let (plain, ranges) = if ansi {
                let plain = s.as_bytes().into_text().ok()?.to_string();
                let ranges = split_fn(&plain);
                (plain, ranges)
            } else {
                let ranges = split_fn(&s);
                (s, ranges)
            };

            if let Some(c) = require_column {
                let is_no_match = match &split_clone {
                    Split::Delimiter(_) | Split::Regexes(_) | Split::CSV(_) => ranges
                        .get(c)
                        .is_none_or(|&(start, end)| start == 0 && end == 0),

                    _ => plain.is_empty(),
                };

                if is_no_match {
                    return None;
                }
            }

            Some((Err(plain), ranges))
        })
    };

    // Build text preprocessor (returns parsed text if ANSI enabled)
    let text_preprocessor: Arc<dyn Fn(&String) -> ConfigPreprocessedData + Send + Sync> = {
        let split_fn = split_fn.clone();
        Arc::new(move |item: &String| {
            let s = if trim {
                item.trim().to_string()
            } else {
                item.clone()
            };

            if ansi {
                match s.as_bytes().into_text() {
                    Ok(mut text) => {
                        text::scrub_text_styles(&mut text);
                        let plain = text.to_string();
                        let ranges = split_fn(&plain);
                        (Ok(text), ranges)
                    }
                    Err(_) => {
                        let ranges = split_fn(&s);
                        (Err(s), ranges)
                    }
                }
            } else {
                let ranges = split_fn(&s);
                (Err(s), ranges)
            }
        })
    };

    // Build the per-column range-lookup factory. Given a column index `n`,
    // returns a closure that maps an input `&String` to the extracted
    // substring of its `n`-th segment. The trim/ansi handling mirrors
    // `text_preprocessor` so the returned substring matches what a column
    // would render. We return the substring directly (as `Cow<'_, str>`)
    // rather than byte ranges, because when ANSI is enabled the ranges
    // index into a plain post-strip string and would not be usable to
    // slice the original `&String`.
    //
    // The inner closure is built via a helper function so the HRTB lifetime
    // (`for<'a> Fn(&'a String) -> Cow<'a, str>`) is propagated to the cast.
    fn make_lookup(
        split_fn: Arc<dyn Fn(&str) -> Vec<(u32, u32)> + Send + Sync>,
        n: usize,
        ansi: bool,
        trim: bool,
    ) -> impl for<'a> Fn(&'a String) -> Cow<'a, str> + Send + Sync + 'static {
        move |item: &String| {
            let s: &str = if trim { item.trim() } else { item.as_str() };
            if ansi {
                let plain = s
                    .as_bytes()
                    .into_text()
                    .map(|text| text.to_string())
                    .unwrap_or_else(|_| s.to_string());
                let ranges = split_fn(&plain);
                let (start, end) = ranges.get(n).copied().unwrap_or((0, 0));
                let start = start.min(plain.len() as u32) as usize;
                let end = end.min(plain.len() as u32) as usize;
                Cow::Owned(plain[start..end].to_string())
            } else {
                let ranges = split_fn(s);
                let (start, end) = ranges.get(n).copied().unwrap_or((0, 0));
                let start = start.min(s.len() as u32) as usize;
                let end = end.min(s.len() as u32) as usize;
                Cow::Borrowed(&s[start..end])
            }
        }
    }

    let ranges_fn: RangesFactory<String> = {
        let split_fn = split_fn.clone();
        Arc::new(move |n: usize| -> RangesFn<String> {
            Arc::new(make_lookup(split_fn.clone(), n, ansi, trim))
        })
    };

    // Build columns
    let columns: Vec<Column<String, ConfigPreprocessedData>> = column_names
        .iter()
        .enumerate()
        .map(|(i, name)| {
            Column::new(
                name.clone(),
                move |_item: &String, d: &ConfigPreprocessedData| {
                    let (text_result, ranges) = d;
                    let range = ranges.get(i).copied().unwrap_or((0, 0));

                    match text_result {
                        Ok(text) => {
                            let mut t =
                                text::slice_ratatui_text(text, range.0 as usize..range.1 as usize);
                            if sanitize {
                                text::apply_to_lines(&mut t, text::sanitize_line);
                            };
                            t
                        }
                        Err(s) => {
                            let s = &s[range.0 as usize..range.1 as usize];
                            if sanitize {
                                Text::from(sanitize_string(s))
                            } else {
                                Text::from(s)
                            }
                        }
                    }
                },
            )
            .with_raw(move |_item: &String, d: &ConfigPreprocessedData| {
                let (_text_result, ranges) = d;
                let range = ranges.get(i).copied().unwrap_or((0, 0));

                match _text_result {
                    Err(s) => Cow::Borrowed(&s[range.0 as usize..range.1 as usize]),
                    Ok(text) => {
                        let s = text.to_string();
                        Cow::Owned(s[range.0 as usize..range.1 as usize].to_string())
                    }
                }
            })
        })
        .collect();

    (columns, raw_preprocessor, text_preprocessor, ranges_fn)
}

/// Resolve the default column index from `cc.default`, looking up the name in
/// the `Vec<Column>` returned by [`build_columns`].
///
/// This must be called *after* `build_columns` so that the column names it
/// sees reflect any truncation done inside `build_columns` (e.g. for
/// `Split::Delimiter` with unnamed capture groups, or `Split::Regexes`).
pub fn default_column(
    cc: &ColumnsConfig,
    columns: &[Column<String, ConfigPreprocessedData>],
) -> usize {
    let column_names: Vec<Arc<str>> = columns.iter().map(|c| c.name.clone()).collect();
    let offset = !cc.names_from_zero as usize;

    match cc.default {
        StringOrInt::String(ref s) => column_names
            .iter()
            .position(|name| name.as_ref() == s.as_str())
            .unwrap_or_else(|| {
                cba::wbog!("Default column '{s}' not found, defaulting to first.");
                0
            }),
        StringOrInt::Int(i) => {
            let i = i.saturating_sub(offset) as usize;
            if i < column_names.len() {
                i
            } else {
                cba::wbog!("Default column index {i} out of bounds, defaulting to first.");
                0
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Minimal `ColumnsConfig` for preprocessor tests: a single column with
    /// `Split::None`. The preprocessor tests below don't care about the
    /// column name, only the string handling.
    fn test_cc() -> ColumnsConfig {
        ColumnsConfig::default()
    }

    #[test]
    fn test_sanitize_preprocessors() {
        let options = PreprocessConfig {
            ansi: true,
            trim: false,
            require_column: None,
            sanitize: true,
        };
        let (_columns, raw_preprocessor, text_preprocessor, _) = build_columns(&test_cc(), options);

        // Input with a tab character, carriage return, and normal characters
        let input = "hello\tworld\r".to_string();

        // 1. Check raw_preprocessor (should NOT sanitize, but ansi: true strips \r)
        let raw_res = raw_preprocessor(&input).unwrap();
        match &raw_res.0 {
            Err(s) => assert_eq!(s, "hello\tworld"),
            _ => panic!("Expected Err(String) containing the raw string"),
        }

        // Check raw_preprocessor without ansi (should be completely untouched)
        let options_no_ansi_raw = PreprocessConfig {
            ansi: false,
            trim: false,
            require_column: None,
            sanitize: true,
        };
        let (_, raw_preprocessor_no_ansi, _, _) = build_columns(&test_cc(), options_no_ansi_raw);
        let raw_res_no_ansi = raw_preprocessor_no_ansi(&input).unwrap();
        match &raw_res_no_ansi.0 {
            Err(s) => assert_eq!(s, &input),
            _ => panic!("Expected Err(String)"),
        }

        // 2. Check text_preprocessor (should sanitize in cell format, but preprocessor returns parsed tui text)
        let text_res = text_preprocessor(&input);
        match &text_res.0 {
            Ok(text) => {
                let plain = text.to_string();
                // Carriage return was already stripped by into_text(), tab is preserved
                assert_eq!(plain, "hello\tworld");
            }
            Err(s) => {
                panic!("Expected Ok(Text), got Err({})", s);
            }
        }

        // 3. Test non-ANSI input sanitization
        let options_no_ansi = PreprocessConfig {
            ansi: false,
            trim: false,
            require_column: None,
            sanitize: true,
        };
        let (_, _, text_preprocessor_no_ansi, _) = build_columns(&test_cc(), options_no_ansi);
        let text_res_no_ansi = text_preprocessor_no_ansi(&input);
        match &text_res_no_ansi.0 {
            Err(s) => {
                assert_eq!(s, &input);
            }
            _ => panic!("Expected Err(String) for non-ansi path"),
        }
    }

    // ---- CSV/TSV split tests -------------------------------------------------

    use crate::config::{ColumnSetting, Split};

    /// Build a `ColumnsConfig` with a CSV/TSV split and a given number of
    /// autogenerated columns (default `max_columns: 6`).
    fn csv_cc(tab: bool) -> ColumnsConfig {
        let mut cc = ColumnsConfig::default();
        cc.split = Split::CSV(tab);
        // max_columns: 6 by default -> col_count: 6
        cc
    }

    /// Run the input through the text preprocessor and return ranges + the
    /// post-trim string, so tests can both inspect raw ranges and slice the
    /// string to verify the extracted fields.
    fn csv_split(input: &str, tab: bool) -> (String, Vec<(u32, u32)>) {
        let options = PreprocessConfig {
            ansi: false,
            trim: false,
            require_column: None,
            sanitize: false,
        };
        let (_columns, _raw_pp, text_pp, _) = build_columns(&csv_cc(tab), options);
        let (text_res, ranges) = text_pp(&input.to_string());
        let plain = match text_res {
            Err(s) => s,
            Ok(t) => t.to_string(),
        };
        (plain, ranges)
    }

    fn field_values<'a>(s: &'a str, ranges: &'a [(u32, u32)]) -> Vec<&'a str> {
        ranges
            .iter()
            .map(|&(start, end)| &s[start as usize..end as usize])
            .collect()
    }

    #[test]
    fn test_split_csv_basic() {
        let (s, ranges) = csv_split("a,b,c", false);
        assert_eq!(field_values(&s, &ranges), vec!["a", "b", "c"]);
    }

    #[test]
    fn test_split_csv_empty_fields() {
        // Leading, trailing, and consecutive delimiters all produce empty fields.
        let (s, ranges) = csv_split(",a,,b,", false);
        assert_eq!(field_values(&s, &ranges), vec!["", "a", "", "b", ""]);
    }

    #[test]
    fn test_split_csv_quoted_field_with_delimiter() {
        // The comma inside the quoted field is literal; surrounding quotes are
        // excluded from the range.
        let (s, ranges) = csv_split("\"a,b\",c", false);
        assert_eq!(field_values(&s, &ranges), vec!["a,b", "c"]);
    }

    #[test]
    fn test_split_csv_escaped_quote() {
        // The ranges index into the *original* string, so `""` is preserved
        // as two literal `"` bytes. Downstream code that wants the decoded
        // value can replace `""` -> `"`.
        let (s, ranges) = csv_split("\"a\"\"b\",c", false);
        assert_eq!(field_values(&s, &ranges), vec!["a\"\"b", "c"]);
    }

    #[test]
    fn test_split_csv_newline_in_quoted_field() {
        // Newlines inside a quoted field are literal content, not record
        // terminators (the splitter only sees one line at a time, so we
        // verify the field keeps the embedded newline).
        let (s, ranges) = csv_split("\"a\nb\",c", false);
        assert_eq!(field_values(&s, &ranges), vec!["a\nb", "c"]);
    }

    #[test]
    fn test_split_csv_strict_quote_mid_field() {
        // Per RFC 4180, a `"` that is not at the start of a field is literal.
        let (s, ranges) = csv_split("a\"b,c", false);
        assert_eq!(field_values(&s, &ranges), vec!["a\"b", "c"]);
    }

    #[test]
    fn test_split_csv_unclosed_quote() {
        // An unclosed quote is treated as if it never closed; everything
        // (including any internal delimiter) becomes the field value.
        let (s, ranges) = csv_split("\"a,b,c", false);
        assert_eq!(field_values(&s, &ranges), vec!["a,b,c"]);
    }

    #[test]
    fn test_split_csv_empty_quoted_field() {
        let (s, ranges) = csv_split("\"\",a", false);
        assert_eq!(field_values(&s, &ranges), vec!["", "a"]);
    }

    #[test]
    fn test_split_tsv() {
        // Same rules, but with tab as the delimiter.
        let (s, ranges) = csv_split("a\tb\tc", true);
        assert_eq!(field_values(&s, &ranges), vec!["a", "b", "c"]);

        // Comma is literal in TSV mode.
        let (s, ranges) = csv_split("a,b\tc", true);
        assert_eq!(field_values(&s, &ranges), vec!["a,b", "c"]);
    }

    #[test]
    fn test_split_csv_truncates_to_col_count() {
        // Use 3 explicit columns and a 5-field line. Extra fields merge into
        // the final column, matching the Delimiter (no-capture) behavior.
        let options = PreprocessConfig {
            ansi: false,
            trim: false,
            require_column: None,
            sanitize: false,
        };
        let mut cc = ColumnsConfig::default();
        cc.split = Split::CSV(false);
        cc.names = vec![
            ColumnSetting {
                name: "a".to_string().into(),
                ignore: false,
                hidden: false,
                options: Default::default(),
            },
            ColumnSetting {
                name: "b".to_string().into(),
                ignore: false,
                hidden: false,
                options: Default::default(),
            },
            ColumnSetting {
                name: "c".to_string().into(),
                ignore: false,
                hidden: false,
                options: Default::default(),
            },
        ];
        let (_columns, _raw_pp, text_pp, _) = build_columns(&cc, options);

        let (text_res, ranges) = text_pp(&"1,2,3,4,5".to_string());
        let s = match text_res {
            Err(s) => s,
            Ok(t) => t.to_string(),
        };
        // 3 columns: first two fields, then the rest merged into the last.
        assert_eq!(field_values(&s, &ranges), vec!["1", "2", "3,4,5"]);
    }

    #[test]
    fn test_split_csv_serde_tokens() {
        use crate::config::Split;

        // Split is deserialized as a field of a surrounding struct, so test
        // the roundtrip with a small wrapper.
        #[derive(serde::Deserialize, serde::Serialize)]
        struct Wrap {
            split: Split,
        }

        let w: Wrap = toml::from_str(r#"split = "csv""#).unwrap();
        assert_eq!(w.split, Split::CSV(false));

        let w: Wrap = toml::from_str(r#"split = "tsv""#).unwrap();
        assert_eq!(w.split, Split::CSV(true));

        // Round-trip via Serialize -> Deserialize.
        for original in [Split::CSV(false), Split::CSV(true)] {
            let serialized = toml::to_string(&Wrap {
                split: original.clone(),
            })
            .unwrap();
            let parsed: Wrap = toml::from_str(&serialized).unwrap();
            assert_eq!(parsed.split, original);
        }
    }

    // ---- ranges_fn tests --------------------------------------------------

    /// Build a `ColumnsConfig` with a CSV split and three named columns.
    fn three_col_csv_cc() -> ColumnsConfig {
        use crate::config::ColumnSetting;
        let mut cc = ColumnsConfig::default();
        cc.split = Split::CSV(false);
        cc.names = vec![
            ColumnSetting {
                name: "a".to_string().into(),
                ignore: false,
                hidden: false,
                options: Default::default(),
            },
            ColumnSetting {
                name: "b".to_string().into(),
                ignore: false,
                hidden: false,
                options: Default::default(),
            },
            ColumnSetting {
                name: "c".to_string().into(),
                ignore: false,
                hidden: false,
                options: Default::default(),
            },
        ];
        cc
    }

    fn build_ranges(tab: bool, ansi: bool) -> RangesFactory<String> {
        let options = PreprocessConfig {
            ansi,
            trim: false,
            require_column: None,
            sanitize: false,
        };
        let mut cc = three_col_csv_cc();
        if tab {
            cc.split = Split::CSV(true);
        }
        let (_, _, _, ranges_fn) = build_columns(&cc, options);
        ranges_fn
    }

    #[test]
    fn test_ranges_fn_csv_basic() {
        let ranges_fn = build_ranges(false, false);
        let input = "alpha,beta,gamma".to_string();

        assert_eq!(ranges_fn(0)(&input), "alpha");
        assert_eq!(ranges_fn(1)(&input), "beta");
        assert_eq!(ranges_fn(2)(&input), "gamma");
    }

    #[test]
    fn test_ranges_fn_out_of_bounds() {
        let ranges_fn = build_ranges(false, false);
        let input = "alpha,beta".to_string();
        // Only 3 columns in this config (a, b, c), but the 3rd field here is
        // empty. An index past col_count returns an empty substring.
        assert_eq!(ranges_fn(99)(&input), "");
    }

    #[test]
    fn test_ranges_fn_ansi_strips_before_splitting() {
        // ANSI prefix must be stripped so the returned substring is the plain
        // text, not the raw escape-encoded bytes.
        let ranges_fn = build_ranges(false, true);
        // "alpha" coloured red, then ",", then "beta", then ",", then "gamma".
        let input = "\x1b[31malpha\x1b[0m,beta,gamma".to_string();

        assert_eq!(ranges_fn(0)(&input), "alpha");
        assert_eq!(ranges_fn(1)(&input), "beta");
        assert_eq!(ranges_fn(2)(&input), "gamma");
    }

    #[test]
    fn test_ranges_fn_tsv() {
        let ranges_fn = build_ranges(true, false);
        let input = "alpha\tbeta\tgamma".to_string();
        assert_eq!(ranges_fn(1)(&input), "beta");
    }
}
