[binds]
"ctrl-s" = "@show"
"ctrl-shift-s" = "@diff"

"@reload" = "ReloadNext"
"@reload_2" = "ReloadPrev"

"@diff" = "Execute({ git --paginate diff --color=always --exit-code {1} && echo no change; })"
"@show" = "Execute(git --paginate show --color=always {1})"

[results]
inactive.fg = "DarkGray"
style.fg = "White"
# inactive_current.modifier = "DIM"

[envs]
DFT_COLOR = "always"
