[start]
directory = { value = "git rev-parse --show-toplevel", exec = true }

[binds]
"ctrl-s" = "@show"
"ctrl-shift-s" = "@diff"

"@reload" = ["#next view", "ReloadNext"]
"@reload_2" = ["#prev view", "ReloadPrev"]

"@diff" = "Execute({ git --paginate diff --color=always --exit-code {1} && echo no change; })"
"@show" = "Execute(git --paginate show --color=always {1} -- {$0})"

[results]
inactive.fg = "DarkGray"
# inactive.modifier = "DIM"
inactive.bg = "Black"

style.fg = "White"
# inactive_current.modifier = "DIM"

[envs]
DFT_COLOR = "always"

[exit]
abort_empty = false

[preview]
show = true
