# grep for a line of change
source = 'base.toml'

[start]
# use x1f because awk cannot print null
command = '''
git log -Dp |
awk -v OFS='\x00' '
/^commit [0-9a-f]/ {
    commit = substr($2, 1, 7)
}
/^diff --git / {
    idx = index($0, " b/")
    if (idx > 0) {
        file = substr($0, idx + 3)
    }
}
/^[+-]/ && !/^(---|\+\+\+) / {
    print commit, file, $0
}
'
'''

[exit]
abort_empty = false

[columns]
split = "\\x00"
max = 3
default = 3

[matcher]
sort = 40

# --- Preview ---
[previewer]
always_trigger = false

[[preview.layout]]
side = "top"
percentage = 50
min = 5
max = 50
command = '''
git diff --color=always {1}\^ {1} -- {2} ||
git show --color=always {1} -- {2}
'''

[[preview.layout]]
command = '''
git show --color=always --stat --summary {1}
'''
side = "right"
percentage = 40
min = 30
max = 120

[[preview.layout]]
command = '''
git show --color=always {1} -- {2}
'''

# --- UI ---
[tui]
percentage = 100

[query]
prompt = "grep> "

[binds]
"@next" = "BecomeSilent(mm -o git/status)"
"@prev" = "BecomeSilent(mm -o git/switch)"

# --- Scripts ---
