# grep for a line of change

[start]
command = '''
git log -Dp |
awk '
BEGIN {
    OFS = "\x1f"
}
/^commit [0-9a-f]/ {
    commit = substr($2, 1, 7)
}
/^diff --git / {
    idx = index($0, " b/")
    if (idx > 0) {
        file = substr($0, idx + 3)
    }
}
/^[+-]/ && !/^(---|\+\+\+) / {
    print commit, file, $0
}
'
'''
command_input_separator = "\\n"

[columns]
split = "\\x1f"
max = 3
default = 3

[matcher]
sort = 20

# --- Preview ---
[previewer]
always_trigger = false

[[preview.layout]]
side = "top"
percentage = 50
min = 5
max = 50
command = '''
DFT_COLOR=always git diff --color=always {1}\^ {1} -- {2} ||
git show {1}:{2}
'''

[[preview.layout]]
command = '''
git -c color.ui=always show --stat --summary {1}
'''
side = "right"
percentage = 40
min = 30
max = 120

[[preview.layout]]
command = '''
git show {1}:{2}
'''

# --- UI ---
[tui]
percentage = 100
