# restore a file or revision

[start]
command = '''
git status --porcelain -z |
while IFS= read -r -d '' line; do
 st=${line:0:2}
 file=${line:3}
 printf '%s\x1f%s\n' "$file" "$st"
done
'''

[columns]
split = "\\x1f"
max = 2
default = 1

[matcher]
sort = 20

[envs]
DFT_COLOR = "always"

# --- Preview ---
[previewer]
always_trigger = false

[[preview.layout]]
command = '''
git diff --color=always --exit-code {1} && echo "no change"
'''
# side = "right"
# percentage = 40
# min = 30
# max = 120

[[preview.layout]]
command = '''
git diff --cached --color=always --exit-code {1} && echo "no staged changes"
'''
side = "right"
percentage = 40
min = 30
max = 120

[[preview.layout]]
# git -c color.ui=always log --decorate --stat --summary -p -- {1}
command = '''
git -c  color.ui=always log --ext-diff -D -p -- {1}
'''

# --- UI ---
[tui]
percentage = 100

[binds]
# --- Scripts ---
# "@stage" = ""
# "@unstage" = ""
# "@restore" = ""
# "@ignore" = ""
# "@delete" = ""
# "@stash" = ""
# "@force_delete" = ""
