# interactive git status
source = 'base.toml'

[start.command]
command = '''
git status --ignore-submodules=dirty -sz |
while IFS= read -r -d '' entry; do
  st_staged="${entry:0:1}"
  st_worktree="${entry:1:1}"
  st=""
  file="${entry:3}"

  RED=$'\033[31m'
  GREEN=$'\033[32m'
  RESET=$'\033[m'

  case "$st_staged" in
    " "|\?) st="" ;;
    *) st="${GREEN}${st_staged}${RESET}"
  esac

  case "$st_worktree" in
    " ") st+=" " ;;
    \?)  st+="${RED}??${RESET}" ;;
    *) st+="${RED}${st_worktree}${RESET}" ;;
  esac

  printf '%s\0%s\n' "$file" "$st"
done
'''

[start]
ansi = true
directory = { value = "git rev-parse --show-toplevel", exec = true }

[columns]
split = "\\x00"
max = 2
default = 1

[matcher]
sort = 40

[exit]
# abort_empty = false

# --- Preview ---
[previewer]
always_trigger = false

[[preview.layout]]
command = '''
git diff --color=always --exit-code {1} && if [ -e {1} ]; then $PAGER {1}; else git show HEAD:{1}; fi
'''
border = { type = "LightDoubleDashed", color = "DarkGray" }
side = "top"
percentage = 50
min = 5
padding = 0

[[preview.layout]]
command = '''
git diff --cached --color=always --exit-code {1} && echo "no staged changes"
'''
border = { type = "LightDoubleDashed", color = "DarkGray" }
side = "top"
percentage = 50
min = 5
padding = 0

[[preview.layout]]
# alternate history: git -c color.ui=always log --decorate --stat --summary -p -- {1}
command = '''
git -c  color.ui=always log --ext-diff -D -p -- {1}
'''

# --- UI ---
[tui]
percentage = 100

[query]
prompt = "status> "

[binds]
"@accept" = ["#stage", "@stage", "Reload"]
"@accept_2" = ["#print", "Print({=1})", "Quit"]
"@next" = "BecomeSilent(mm -o git/restore)"
"@prev" = "BecomeSilent(mm -o git/grep)"

"ctrl-1" = "@summary"
"ctrl-u" = ["@unstage", "Reload"]
"ctrl-c" = ["@commit", "Quit"]
"alt-c" = ["Execute(git add . && echo 'All changes staged' || echo 'git add . failed')", "@commit", "Quit"]
"ctrl-shift-c" = ["@commit_ai", "Reload"]
"alt-r" = ["@restore", "Reload"]
"ctrl-t" = ["@stash", "Reload"]
"@rm" = ["#untrack", "@untrack", "Reload"]
"ctrl-shift-d" = ["@delete", "Reload"]
"alt-d" = ["@disk-delete", "Reload"]
"alt-i" = ["@ignore", "Reload"]

# --- Scripts ---
"@summary" = "RunPreview(git -c color.ui=always status -sbu && echo && git --no-pager diff --color=always --compact-summary && false)"

"@rename" = '''ExecuteOrConfirm(
set -- {+1}
echo "Rename $1 to: "
read -r new_name
[ -n "$new_name" ] || exit
mkdir -p "$(dirname "$new_name")"
git mv "$1" "$new_name"
)
'''

"@stage" = '''
ExecuteAsync(
set -e
set -- {+1}
ac=true
ad=true

for f; do
  if [ -n "$(git ls-files --others --exclude-standard -- "$f")" ]; then
      ac=false
  elif git diff --quiet -- "$f"; then
      ad=false
  else
      ac=false
  fi
done

$ac || $ad
if $ad; then git add -- "$@"; else git reset -q -- "$@"; fi
)
'''

"@unstage" = '''
ExecuteAsync(
set -e

if ((MM_SELECT_COUNT)); then
  set -- {+1}
else
  set -- .
fi

ac=true
ad=true

for f; do
  git diff --cached --quiet -- "$f" && ad=false || ac=false
done

if $ac; then
  git add -- "$@"
else
  git reset -q -- "$@"
fi
)
'''

"@restore" = '''
Execute(
set -e
set -- {+1}
if (( $# == 1 )); then
  file="$1"
  if git diff --cached --quiet -- "$file" 2>/dev/null; then
    printf "Restore %s to HEAD? [y/N] " "$file"
  else
    printf "Restore %s to HEAD? [y(HEAD)/N/s(taging)] " "$file"
  fi
  read -r ans
  case "$ans" in
    [yY]*) git restore --source=HEAD --staged --worktree -- "$file" ;;
    [sS]*) git restore -- "$file" ;;
  esac
else
  printf "Restore %d files? [y(HEAD)/N/s(taging)] " "$#"
  read -r ans
  case "$ans" in
    [yY]*) git restore --source=HEAD --staged --worktree -- "$@" ;;
    [sS]*) git restore -- "$@" ;;
  esac
fi
)
'''

"@stash" = '''
Execute(
set -e
printf "Stash message (optional): "
read -r msg
if [ -n "$msg" ]; then
  git stash push -m "$msg" -- {+1}
else
  git stash push -- {+1}
fi
)
'''

"@untrack" = '''
ExecuteOrConfirm(
set -e

tracked=$(git ls-files -z --cached --exclude-standard -- {+1})
printf '%s' "$tracked" |
while IFS= read -r -d '' file; do
  files+=("$file")
done

[ ${#files[@]} -eq 0 ] && echo "No tracked files selected" && exit 1

if git rm --cached -n -- "${files[@]}" >/dev/null; then
  git rm --cached -- "${files[@]}"
else
  printf "Force untrack ${#files} files? [y/N] "
  read -r ans
  case "$ans" in
    [yY]*) git rm --cached -f -- "${files[@]}" ;;
  esac
fi
)
'''

"@disk-delete" = "ExecuteOrConfirm(rm -rf -- {+1})"

"@delete" = '''
ExecuteOrConfirm(
git add -- {+1}
git rm -rf -- {+1}
)
'''

"@ignore" = '''
ExecuteOrConfirm(
set -e
for f in {+1}; do
  git rm -r --cached "$f" 2>/dev/null &&
  echo "$f" >> .gitignore
done
)
'''

"@commit" = '''
Execute(
set -e
if git diff --cached --quiet; then
  git add .
fi
git --no-pager diff --cached --compact-summary
echo
echo "Commit message: "
msg=""
while IFS= read -r line; do
  if [[ "$line" == *'\' ]]; then
    msg+="${line%?}"$'\n'
    printf "> "
  else
    msg+="$line"
    break
  fi
done

if [ -n "$msg" ]; then
  git commit -m "$msg"
else
  git commit
fi
)
'''

# "@commit_ai" = '''
# Execute(:)
# '''
