# Intelligently switch to any ref
source = 'base.toml'

[start]
command = '''
git for-each-ref --format='%(objectname:short) %(refname:strip=2)' refs/heads
git remote |
while read -r remote; do git for-each-ref --format="%(objectname:short) %(refname)" "refs/remotes/$remote/" |
grep -v '/HEAD$' |
sed "s| refs/remotes/$remote/| $remote:|"; done
'''
additional_commands = [
  "",
  "git for-each-ref --format='%(objectname:short) %(refname:lstrip=2)' refs/tags",
  "git ls-remote --heads --tags ${1:-origin} | awk '{print substr($1,1,7), $2}'",
]

[columns]
split = " "
max = 2
default = 2

[matcher]
sort = 40

# --- Preview ---
[previewer]
always_trigger = false

[[preview.layout]]
command = '''
set -- $(git rev-list --left-right --count HEAD...{1})
behind=$1
ahead=$2
commits=$(git rev-list --count {1})
echo "behind: $behind ahead: $ahead commits: $commits"
printf "%${COLUMNS}s\n" | tr ' ' '-'
git log --color=always --left-right --oneline ...{1}
'''
# side = "right"
# percentage = 40
# min = 30
# max = 120

[[preview.layout]]
command = '''
echo {1}..
printf "%${COLUMNS}s\n" | tr ' ' '-'
git diff --color=always --exit-code {1} -- {$0} && echo "no change"
'''
# side = "top"
# percentage = 50
# min = 5
# max = 50

[[preview.layout]]
command = '''
git log --color=always --graph --decorate --pretty=oneline --abbrev-commit {1}
'''
# side = "right"
# percentage = 75
# min = 5
# max = 240

[[preview.layout]]
command = '''
git log --color=always --stat --summary --decorate {1}
'''
side = "right"
percentage = 40
min = 30
max = 120
border.type = "Plain"
border.padding = [2, 0]

# --- UI ---
[tui]
percentage = 100

[query]
prompt = "switch> "

[binds]
"@accept" = "@switch"
"@accept_2" = ["@switch_silent", "Reload"]
"@rm" = ["@delete", "Reload"]

"ctrl-u" = ["@update", "Reload"]
"ctrl-a" = ["@add_remote", "Reload"]
"ctrl-n" = ["@add_branch", "Reload"]
"alt-r" = ["@show_remotes"]

"@next" = "BecomeSilent(mm -o git/grep)"
"@prev" = "BecomeSilent(mm -o git/restore)"

# --- Scripts ---
"Start" = '''Transform(
    HEADERS=(
      branches
      tags
      remotes
    )
    setopt KSH_ARRAYS 2>/dev/null
    ref="$(git symbolic-ref --short HEAD 2>/dev/null || git rev-parse --short HEAD)"
    echo "SetHeader(${HEADERS[$MM_INDEX]} ($ref))"
)
'''
"Reloaded" = '''Transform(
    HEADERS=(
      branches
      tags
      remotes
    )
    setopt KSH_ARRAYS 2>/dev/null
    ref="$(git symbolic-ref --short HEAD 2>/dev/null || git rev-parse --short HEAD)"
    echo "SetHeader(${HEADERS[$MM_INDEX]} ($ref))"
)
'''

"@update" = '''
ExecuteOrConfirm(
set -e
case "$MM_INDEX" in
0)
    ref={2}
    if [[ "$ref" == *":"* ]]; then
        remote="${ref%%:*}"
        echo "Fetching $remote..."
        git fetch "$remote"
    else
        current="$(git branch --show-current)"
        git switch "$ref"
        echo "Updating branch $ref..."
        git pull --rebase --autostash
        git status -sb
        git switch "$current"
    fi
    ;;
1)
    echo "Fetching tags..."
    git fetch --tags
    ;;
2)
    remote="$(git config --get branch.$(git branch --show-current).remote)"
    echo "Fetching $remote..."
    git fetch $remote
    ;;
esac
false
)
'''

# Switch and exit: less spurious than switch_silent
"@switch" = '''
Become(
set -e
if [ -n "$(git status --porcelain)" ]; then
    printf "Local changes detected, continue? [y/N/stash] "
    read -r ans
    case "$ans" in
        [sS]*) git stash ;;
        [yY]*) ;;
        *) exit 0 ;;
    esac
fi

remote="$(git config --get branch.$(git branch --show-current).remote)"

case "$MM_INDEX" in
0)
  ref={2}
  ref=${ref#*:}
  git switch "$ref"
  ;;
1)
  git switch --detach {2}
  ;;
2)
  ref={2}
  case "$ref" in
    refs/heads/*)
      name="${ref#refs/heads/}"
      git fetch "$remote" "$ref:$name"
      if git rev-parse --verify --quiet "$name"; then
          git switch "$name" && git branch --set-upstream-to="$remote/$name"
      else
          git switch -c "$name" --track "$remote/$name"
      fi
      ;;
    refs/tags/*)
      git fetch "$remote" "$ref"
      git switch --detach FETCH_HEAD
      ;;
  esac
  ;;
esac
)
'''

"@switch_silent" = '''ExecuteOrConfirm(
set -e
case "$MM_INDEX" in
0)
    ref={2}
    ref=${ref#*:}
    git switch "$ref"
    ;;
1)
    git switch --detach {2}
    ;;
2)
    ref={2}
    case "$ref" in
    refs/heads/*)
        name="${ref#refs/heads/}"
        git fetch "$remote" "$ref:$name"
        git switch -c "$name" --track "$remote/$name"
        ;;
    refs/tags/*)
        git fetch "$remote" "$ref"
        git switch --detach FETCH_HEAD
        ;;
    esac
;;
esac
)'''

"@delete" = '''
ExecuteOrConfirm(
set -e
case "$MM_INDEX" in
0)
    ref={2}
    if [[ "$ref" == *":"* ]]; then
         remote="${ref%%:*}"
         branch="${ref#*:}"
         if [ -n "$remote" ] && [ -n "$branch" ]; then
             printf "Do you want to DELETE remote branch '%s' from '%s'? [y/N]: " "$branch" "$remote"
             read -r confirm
             case "$confirm" in
                 [Yy]*)
                     echo "Deleting remote branch..."
                     git push "$remote" --delete "$branch"
                     ;;
                 *)
                     echo "Operation canceled."
                     exit 0
                     ;;
             esac
         else
             echo "Error: Invalid ref format. Expected 'remote:branch'."
             exit 1
         fi
    else
        printf "Delete local branch %s? [y/N] " "$ref"
        read -r ans

        case "$ans" in
            [yY]*)
                git branch -D "$ref"

                upstream="$(git rev-parse --abbrev-ref "$ref@{u}" 2>/dev/null || true)"

                if [ -n "$upstream" ]; then
                    remote="${upstream%%/*}"
                    branch="${upstream#*/}"

                    printf "Also delete remote branch %s/%s? [y/N] " "$remote" "$branch"
                    read -r rans

                    case "$rans" in
                        [yY]*)
                            git push "$remote" --delete "$branch"
                            ;;
                    esac
                fi
                ;;
        esac
    fi
    ;;
1)
    set -- {+2};
    auto_remote=0
    
    while (($#)); do
        printf "Delete tag $1? [y/N/aA] "
        read -r ans
    
        case "$ans" in
            a|A*)
                git tag -d "$@"
    
                printf "Delete remote tags too? [y/N] "
                read -r rans
    
                case "$rans" in
                    y|Y*)
                        for t in "$@"; do
                            set -- "$@" "refs/tags/$t"
                            shift
                        done
                        
                        git push origin --delete "$@"
                        ;;
                esac
                exit 0
                ;;
            y|Y*)
                git tag -d "$1"
    
                if [ "$auto_remote" -eq 1 ]; then
                    git push origin --delete "refs/tags/$1"
                else
                    printf "Delete remote tag too? [y/N/(all)] "
                    read -r rans
    
                    case "$rans" in
                        a|A*)
                            auto_remote=1
                            git push origin --delete "refs/tags/$1"
                            ;;
                        y|Y*)
                            git push origin --delete "refs/tags/$1"
                            ;;
                    esac
                fi
    
                shift
                ;;
            *)
                shift
                ;;
        esac
    done
    ;;
*)
    echo "Unavailable"
    exit 1
    ;;
esac
)
'''

"@rename" = '''
ExecuteOrConfirm(
set -e
case "$MM_INDEX" in
0)
    ref={2}
    if [[ "$ref" == *":"* ]]; then
        old_remote="${ref%%:*}"
        printf "Rename REMOTE %s to: " "$old_remote"
        read -r new_name
        if [ -n "$new_name" ]; then
            # Rename
            git remote rename "$old_remote" "$new_name"
        else
            # Input was empty -> Prompt to delete
            printf "Do you want to DELETE remote '%s'? [y/N]: " "$old_remote"
            read -r confirm
            
            case "$confirm" in
                [Yy]*)
                    git remote remove "$old_remote"
                    ;;
                *)
                    echo "Operation canceled."
                    exit 0
                    ;;
            esac
        fi
    else
        printf "Rename branch %s to: " "$ref"
        read -r new_name
        [ -n "$new_name" ] || exit
        git branch -m "$ref" "$new_name"

        printf "push? [y/N] "
        read -r ans
        case "$ans" in
        [yY]*)
            git push origin "$new_name" &&
            git push origin --delete "$ref"
            ;;
        [nN]*|'')
            git push origin "$new_name"
            ;;
        esac
    fi
    ;;
1)
    printf "Rename tag %s to: " {2}
    read -r new_tag
    [ -n "$new_tag" ] || exit

    git tag "$new_tag" {2}
    git tag -d {2}

    printf "push? [y/N] "
    read -r ans
    case "$ans" in
        [yY]*)
            git push origin "$new_tag" &&
            git push origin --delete "{2}"
            ;;
        [nN]*|'')
            git push origin "$new_tag"
            ;;
    esac
    ;;
*)
    echo "Unavailable"
    false
    ;;
esac
)
'''

"@add_remote" = '''
ExecuteOrConfirm(
set -e
printf "Remote name: "
read -r name
[ -n "$name" ]
printf "Remote URL: "
read -r url
[ -n "$url" ]
git remote add "$name" "$url"
)
'''

"@add_branch" = '''ExecuteOrConfirm(
set -e
printf "New branch name: "
read -r branch
[ -n "$branch" ] || exit
git switch -c "$branch"
)'''


"@show_remotes" = '''ExecuteOrConfirm(
git remote | while IFS= read -r remote; do
    echo "=== $remote ==="
    git remote show "$remote"
    echo
done
false
)
'''