# Browse known hosts

[start]
command = "grep -v '^[[:space:]]*$' ~/.ssh/known_hosts | sort"

[columns]
split = ' '
max = 4
default = 1
names = [
  "host",
  "type",
  "key",
  { name = "comment", hidden = true },
]

# --- Preview ---
[preview]
show = true

[[preview.layout]]
command = "echo '### Fingerprint ###\n'; echo {} | ssh-keygen -lf -"

[[preview.layout]]
command = "echo '### Fetch ###\n'; ssh-keyscan {host};"

# --- UI ---
[header]
content = ["host", "type", "key"]

[query]
prompt = "known> "
prompt_style.fg = "Blue"
prompt_style.modifier = "ITALIC"

[binds]
"@open" = "Execute(ssh -vT {host} 2>&1)"
"@next" = "BecomeSilent(mm -o ssh/tailscale)"
"@prev" = "BecomeSilent(mm -o ssh/keys)"

# --- Scripts ---
"@rm" = ["Execute(ssh-keygen -R {host})", "Reload"]
