# picker configuration file

[tui]
percentage = 60
min = 10
max = 120

[ui]
# border    = { color = "blue", bg = "#282828" }
tick_rate = 30

[query]
style.fg = "White"
cursor = "default"
prompt = ">"

[header]
content = "test"
header_lines = 2
interactions = [[[0, "test"]], [[1, "test"], [3, "open"], [4, ""]]]

[results]
scroll_padding = 2

# border           = { type = "Rounded", sides = "", padding = 0 }
style.fg = "White"
current.bg = "Black"
current.modifier = "BOLD"
match.fg = "Green"

# reverse = auto
wrap = true

scroll_wrap = true

[status]
style.fg = "Green"
style.modifier = "ITALIC"

[previewer]
try_lossy = false
delay_clear = false
max_procs = 4
always_trigger = true

[preview]
# border      = { type = "Rounded", color = "Blue" }
scroll_wrap = true
show = true
wrap = true

[[preview.layout]]
command = '''
if [ -d {} ]; then
    cd {} &&
    find . -maxdepth 2 | sed 's|[^/]*/|  |g'
else
    cat {}
fi
'''
side = "right"
percentage = 40
min = 30
max = 120
border = { type = "LightDoubleDashed", color = "DarkGray" }

[[preview.layout]]
side = "top"
percentage = 40
min = 30
max = 120
border.type = "Plain"
border.padding = [2, 0]

[binds]
# Essentia
"ctrl-c" = "Quit"
"esc" = "Quit"
"enter" = "@accept"
# "alt-enter" = "@accept_2"
# "ctrl-enter" = "@accept_2" # requires enhancement
"ctrl-a" = "CycleSelections"
"tab" = ["Toggle", "Down"]
"shift-backtab" = ["Toggle", "Up"]

# Edit
### (DEFAULTS) ###
# "right" = "ForwardChar"
# "left" = "BackwardChar"
# "ctrl-right" = "ForwardWord"
# "ctrl-left" = "BackwardWord"
# "backspace" = "DeleteChar"
# "ctrl-h" = "DeleteWord"
# "ctrl-u" = "Cancel"
# "alt-a" = "QueryPos(0)"

# Navigation
"alt-1" = "Pos(0)"
"alt-0" = "Pos(-1)"

### (DEFAULTS) ###
# "up" = "Up"
# "down" = "Down"
# "pagedown" = "HalfPageDown"
# "pageup" = "HalfPageUp"
# "shift-up" = "PreviewHalfPageUp"
# "shift-down" = "PreviewHalfPageDown"
# "ctrl-shift-up" = "VScroll(1)"
# "ctrl-shift-down" = "VScroll(-1)"
# "ctrl-shift-left" = "HScroll(-1)"
# "ctrl-shift-right" = "HScroll(1)"
# "alt-up" = "VScroll(1)"
# "alt-down" = "VScroll(-1)"
# "alt-left" = "HScroll(-1)"
# "alt-right" = "HScroll(1)"
# "ctrl-[" = "ToggleWrap", # requires keyboard enhancement
# "ctrl-]" = "TogglePreviewWrap",  # requires keyboard enhancement
# "alt-{" = "ToggleWrap",
# "alt-}" = "TogglePreviewWrap",

# Columns
"ctrl-." = "NextColumn" # requires keyboard enhancement
"ctrl-shift-." = "PrevColumn" # requires keyboard enhancement
"alt-." = "NextColumn"
"alt-shift-." = "PrevColumn"

# Preview
"ctrl-j" = "PreviewJump"

### (DEFAULTS) ###
# "?" = "SwitchPreview"
# "alt-/" = "NextPreview"
# "alt-shift-/" = "PrevPreview"
# "ctrl-/" = "NextPreview" # requires keyboard enhancement
# "ctrl-shift-/" = "PrevPreview" # requires keyboard enhancement
# "alt-h" = "Help"

"alt-shift-=" = "ExpandPreview"
"alt-+" = "ExpandPreview" # A terminal might only transmit alt-shift-=
"alt-hyphen" = "ShrinkPreview"

# Reserved
"F1" = "@help"
"F2" = "@rename"
"F3" = "@search"
"F4" = "@rm"
"F5" = "@refresh"
"F6" = "@cycle"
"F7" = "@build"
"F8" = "@step"
"F9" = "@toggle"
"F10" = "@menu"
"F11" = "@look"
"F12" = "@save"

# Programmable
"ctrl-l" = "@look" # "maximize" the preview
"ctrl-o" = "@open"
"alt-o" = "@open_2"
"ctrl-r" = "@reload"
"ctrl-shift-r" = "@reload_2"
"ctrl-shift-n" = "@next"
"ctrl-shift-p" = "@prev"
"ctrl-tab" = "@next" # requires keyboard enhancement
"alt-tab" = "@next"
"ctrl-shift-tab" = "@prev"
"ctrl-shift-backtab" = "@prev"
"ctrl-d" = "@rm"
"Delete" = "@rm"
"ctrl-s" = "@show"

"@accept" = "Accept"
"@accept_2" = "Accept"
"@look" = "Execute(eval $MM_PREVIEW_COMMAND | $PAGER)"
"@open" = "ExecuteOrConfirm($EDITOR -- {1})"
"@open_2" = "Become($EDITOR -- {1})"
"@reload" = "Reload"
"@next" = ["ReloadNext", "Cancel"]
"@prev" = ["ReloadPrev", "Cancel"]
"@help" = "Help"
"@refresh" = "Redraw"

# Printing
"alt-p" = "@print"
"alt-shift-p" = "@print_2"
"ctrl-y" = "@copy"
"ctrl-shift-y" = "@copy_all" # requires keyboard enhancement
"alt-shift-y" = "@copy_all"
"alt-y" = "@copy_active"

"@print" = "Print({-})"
"@print_2" = "Print({-!})"
"@copy" = "CopyAsync(printf '%s\n' {+1})"
"@copy_all" = "CopyAsync(printf {})"
"@copy_active" = "CopyAsync(printf '%s\n' {+!})"

# test
"ctrl-t" = "Become(set -e; false; echo hi;)"
"alt-t" = "@test"
"@test" = "Execute(echo ----; read v; echo $v; echo ----)"
"alt-enter" = "Print({1})"

[matcher]
trim = true
sort_threshold = 1

[columns]
split = '\s+'
max = 8

[start]
skip_invalid_lines = true # set false to error on encountering invalid utf-8
[start.command]
cmd = '''
if command -v fd >/dev/null 2>&1; then
    fd --strip-cwd-prefix --print0
else
    find . -print0
fi
'''
separator = "\\0"

[exit]
first = false
