# Unicode Character Database

[start.command]
command = '''zstd -dc "$(dirname -- "$MM_OVERRIDE")"/unicode.zst'''

[envs]
ACTIVE_DICT = "unicode"

[query]
prompt = "unicode> "

[header]
content = ['char', 'name', 'cat']

[columns]
split = ";"
names = ["char", "name", "category"]
default = "name"

[matcher]
prefer_prefix = false

[binds]
"@copy" = '''Transform(
    hex=$(printf "%s" "{char}" | iconv -f UTF-8 -t UTF-32BE | od -A n -t x4 | tr -d ' ' | sed 's/^0*//')
    printf "\\u{%s}" "$hex"
)'''
"@copy_all" = "Copy(echo {char})"
"enter" = ["Print({=char})", "Quit"]
"tty^^enter" = "Copy(echo {char})"

# --- Preview ---

[[preview.layout]]
command = '''
hex=$(printf "%s" "{char}" | iconv -f UTF-8 -t UTF-32BE | od -A n -t x4 | tr -d ' ' | sed 's/^0*//')
printf "%${COLUMNS}s\n" | tr ' ' '-'
echo "  {char}  {name}"
printf "%${COLUMNS}s\n" | tr ' ' '-'
echo "Code:     U+$hex"
echo "Category: {category}"
'''
